#!/bin/bash -xe 
#ref: https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac

brew tap caskroom/cask
brew tap caskroom/versions
brew cask install java8
brew cask install java11
brew install jenv
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
echo 'export JAVA_HOME="$(jenv prefix)"' >> ~/.bash_profile
echo 'eval "$(jenv init -)"' >> ~/.bash_profile
source ~/.bash_profile
jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home
jenv add /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
jenv versions
